# Generated by Django 4.1.1 on 2022-09-24 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomi", models.CharField(max_length=255)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="avto_kategoriyalar/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
            },
        ),
        migrations.CreateModel(
            name="Avtomobil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomi", models.CharField(max_length=200)),
                ("yil", models.IntegerField()),
                (
                    "rasm",
                    models.ImageField(blank=True, null=True, upload_to="avto_rasmlar/"),
                ),
                ("manzil", models.CharField(max_length=200)),
                ("probeg", models.IntegerField()),
                ("kuzov", models.CharField(max_length=200)),
                ("dvigatel", models.CharField(max_length=200)),
                ("rang", models.CharField(max_length=200)),
                (
                    "narx",
                    models.CharField(
                        help_text="So'z ko'rinishida ham yozish mumkin...",
                        max_length=200,
                    ),
                ),
                ("tel_nomer", models.IntegerField()),
                ("egasi", models.CharField(max_length=200)),
                ("yuklangan_sana", models.DateTimeField(auto_now_add=True)),
                ("xarakteristika", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Avtomobil",
                "verbose_name_plural": "Avtomobillar",
            },
        ),
    ]
