# Generated by Django 4.1.1 on 2022-09-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avtomobil",
            name="rasm",
            field=models.ImageField(upload_to="avto_rasmlar/"),
        ),
    ]
